[package]
name = "cw2"
version = "0.14.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Definition and types for the CosmWasm-2 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cosmwasm-std = { git = "https://github.com/polymerdao/cosmwasm", rev = "710c31e12de5decedb6dbb0f322f2feaeeede639", features = ["stargate"] }
cw-storage-plus = { path = "../../packages/storage-plus", version = "0.14.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
